config/routes.rb
Rails.application.routes.draw do
  resources :tags
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :users, only: %i[new create show edit]
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"

  resources :sessions, only: [:new, :create, :destroy]

  get "/privacy", to: "static_pages#index"
  # get '/puraibasi', to: 'static_pages#puraibasi'
  # config/routes.rb

  resources :bookmarks, only: [:create, :destroy]

  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]

  resources :poses do
    collection do
      get :bookmarks
      get :ranking
      get :preview
    end
    get :search, on: :collection
  end
  root "top#index"
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :poses
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_poses, through: :bookmarks, source: :pose
  mount_uploader :avatar, AvatarUploader

  validates :password, length: { minimum: 8 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :name, presence: true, length: { maximum: 10 }
  validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :reset_password_token, uniqueness: true, allow_nil: true

  def own?(object)
    return false if id.nil?
    id == object&.user_id
  end

  def bookmark(pose)
    bookmark_poses << pose
  end

  def unbookmark(pose)
    bookmark_poses.destroy(pose)
  end

  def bookmark?(pose)
    bookmark_poses.include?(pose)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create show]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @poses = Pose.where(user_id: @user.id).order(created_at: :desc).page(params[:page])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: t(".success")
    else
      flash.now[:danger] = t(".failure")
      render :new, status: :unprocessable_entity
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, maxlength: "10"  %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <%= user.name %>さんが投稿した一覧
  </p>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>
<%= render "form", user: @user %>
<br>
<div>
  <%= link_to "Show this users", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Users</h1>
<button type="submit" class="btn btn-primary">Button</button>
<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>
<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto">
      <h1><%= t('.title') %></h1>
      <%= form_with model: @user do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
        <div class="mb-3">
          <%= f.label :name, class: "form-label" %>
          <%= f.text_field :name, class: "form-control", maxlength: "10" %>
        </div>     
        <div class="mb-3">
          <%= f.label :email, class: "form-label" %>
          <%= f.email_field :email, class: "form-control", maxlength: "300" %>
        </div>
        <div class="mb-3">
          <%= f.label :password, class: "form-label" %>
          <%= f.password_field :password, class: "form-control", maxlength: "20" %>
        </div>
        <div class="mb-3">
          <%= f.label :password_confirmation, class: "form-label" %>
          <%= f.password_field :password_confirmation, class: "form-control", maxlength: "20" %>
        </div>
        
        <%# <%= f.label :favorite_genre, class: "好きな写真のジャンル" %> 
        <%# <%= f.radio_button :favorite_genre, "cute" %> <%# 可愛い %>
        <%# <%= f.radio_button :favorite_genre, "cool" %> <%# かっこいい %> 
        <%# <%= f.radio_button :favorite_genre, "funny" %> <%# 面白い %>
        <%# <%= f.submit "登録", class: "btn btn-primary" %> 
        <%= f.submit "登録", class: "btn btn-primary" %>
      <% end %>
      
      <div class='text-center'>
        <%= link_to t('.to_login_page'), login_path %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @user %>
<div class="container pt-3">
  <div id="poses" class="row">
    <% @poses.each do |pose| %>
    <%= render partial: 'poses/pose', locals: { pose: pose } %>
    <% end %>
    <%= paginate @poses, theme: 'bootstrap-5' %>
  </div>
</div>