config/routes.rb
Rails.application.routes.draw do
  resources :tags
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :users, only: %i[new create show edit]
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"

  resources :sessions, only: [:new, :create, :destroy]

  get "/privacy", to: "static_pages#index"
  # get '/puraibasi', to: 'static_pages#puraibasi'
  # config/routes.rb

  resources :bookmarks, only: [:create, :destroy]

  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]

  resources :poses do
    collection do
      get :bookmarks
      get :ranking
      get :preview
    end
    get :search, on: :collection
  end
  root "top#index"
  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/shared/_before_login_header.html.erb
<header>
  <div class= "header-logo"> 
    <%= link_to '/', class: 'navbar-brand' do %>
    <%= image_tag 'logo.png' %> 
    <% end %>
  </div>
  <div class="header-menu">
    <ul class="menu">
      <li class="list">
        <%= link_to t('header.login'), login_path, class: "nav-link" %>            
      </li>
      <li class='list'>
        <%= link_to t('header.pose_index'), poses_path, class: 'nav-link' %>
      </li>
      <li class='list'>       
        <%= link_to t('header.pose_ranking'), ranking_poses_path, class: 'nav-link' %>
      </li>             
    </ul>
  </div>
</header>
<input type="checkbox" id="overlay-input" />
<label for="overlay-input" id="overlay-button"><span></span></label>
<div id="overlay">
  <ul>
    <li class="nav-item">
      <%= link_to t('header.login'), login_path, class: "nav-link" %>            
    </li>
    <li class='nav-item'>
      <%= link_to t('header.pose_index'), poses_path, class: 'nav-link' %>
    </li>
    <li class='nav-item'>       
      <%= link_to t('header.pose_ranking'), ranking_poses_path, class: 'nav-link' %>
    </li>            
  </ul>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer-001"> 
    <%= link_to '/', class: 'navbar-brand' do %>
        <%= image_tag 'logo.png' %> 
    <% end %>
    <nav>
        <ul class="footer-001__list">
            <%= link_to t('links.terms'), privacy_path, class: 'nav-link' %>
        <a href="https://docs.google.com/forms/d/e/1FAIpQLSf9TYrCpOFPBvYvnLhYWCiNRXsCbividOKjMZpSF3Eq2QA-8w/viewform?usp=sf_link" target="_blank" class="nav-link">お問い合わせ</a>     
        </ul>
    </nav>
    <p class="footer-001__copyright">@ 2024 ピス卒</p>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class= "header-logo">
    <%= link_to '/', class: 'navbar-brand' do %>
      <%= image_tag 'logo.png' %> 
    <% end %> 
  </div>
  <div class="header-menu">
    <ul class="menu">
      <li class='list'>
        <%= link_to t('header.pose_index'), poses_path, class: 'nav-link' %>
      </li>
      <li class='list'>
        <%= link_to t('header.pose_bookmark'), bookmarks_poses_path, class: 'nav-link' %>
      </li>
      <li class='list'>
        <%= link_to t('header.profile'), profile_path, class: 'nav-link' %>
      </li>
      <li class='list'>       
        <%= link_to t('header.pose_ranking'), ranking_poses_path, class: 'nav-link' %>
      </li>       
      <li class='list'>
        <%= link_to t('header.logout'), logout_path, class: "nav-link", data: { turbo_method: :delete } %>
      </li>   
    </ul>
  </div>  
</header>
<input type="checkbox" id="overlay-input" />
<label for="overlay-input" id="overlay-button"><span></span></label>
<div id="overlay">
  <ul>
    <li class='nav-item'>
      <%= link_to t('header.pose_index'), poses_path, class: 'nav-link' %>
    </li>
    <li class='nav-item'>
      <%= link_to t('header.pose_bookmark'), bookmarks_poses_path, class: 'nav-link' %>
    </li>
    <li class='nav-item'>
      <%= link_to t('header.profile'), profile_path, class: 'nav-link' %>
    </li>
    <li class='nav-item'>       
      <%= link_to t('header.pose_ranking'), ranking_poses_path, class: 'nav-link' %>
    </li>       
    <li class='nav-item'>
      <%= link_to t('header.logout'), logout_path, class: "nav-link", data: { turbo_method: :delete } %>
    </li>    
  </ul>
</div>

   