config/routes.rb
Rails.application.routes.draw do
  resources :tags
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :users, only: %i[new create show edit]
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"

  resources :sessions, only: [:new, :create, :destroy]

  get "/privacy", to: "static_pages#index"
  # get '/puraibasi', to: 'static_pages#puraibasi'
  # config/routes.rb

  resources :bookmarks, only: [:create, :destroy]

  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]

  resources :poses do
    collection do
      get :bookmarks
      get :ranking
      get :preview
    end
    get :search, on: :collection
  end
  root "top#index"
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :pose_tags, dependent: :destroy
  has_many :poses, through: :pose_tags
  validates :name, length: { in: 1..10 }, uniqueness: true
  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at id id_value name updated_at]
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[show edit update destroy]

  def index
    @tags = Tag.all
  end

  def show; end

  def new
    @tag = Tag.new
  end

  def edit; end

  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tag_url(@tag), notice: "Tag was successfully created." }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to tag_url(@tag), notice: "Tag was successfully updated." }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tag.destroy!

    respond_to do |format|
      format.html { redirect_to tags_url, notice: "Tag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_tag
      @tag = Tag.find(params[:id])
    end

    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/views/tags/_form.html.erb
<%= form_with(model: tag) do |form| %>
  <% if tag.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>
      <ul>
        <% tag.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/_tag.html.erb
<div id="<%= dom_id tag %>">
  <p>
    <strong>Name:</strong>
    <%= tag.name %>
  </p>
</div>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>
<%= render "form", tag: @tag %>

<br>

<div>
  <%= link_to "Show this tag", @tag %> |
  <%= link_to "Back to tags", tags_path %>
</div>

app/views/tags/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Tags</h1>
<div id="tags">
  <% @tags.each do |tag| %>
    <%= render tag %>
    <p>
      <%= link_to "Show this tag", tag %>
    </p>
  <% end %>
</div>
<%= link_to "New tag", new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>
<%= render "form", tag: @tag %>
<br>
<div>
  <%= link_to "Back to tags", tags_path %>
</div>

app/views/tags/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @tag %>
<div>
  <%= link_to "Edit this tag", edit_tag_path(@tag) %> |
  <%= link_to "Back to tags", tags_path %>
  <%= button_to "Destroy this tag", @tag, method: :delete %>
</div>