config/routes.rb
Rails.application.routes.draw do
  resources :tags
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :users, only: %i[new create show edit]
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"

  resources :sessions, only: [:new, :create, :destroy]

  get "/privacy", to: "static_pages#index"
  # get '/puraibasi', to: 'static_pages#puraibasi'
  # config/routes.rb

  resources :bookmarks, only: [:create, :destroy]

  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]

  resources :poses do
    collection do
      get :bookmarks
      get :ranking
      get :preview
    end
    get :search, on: :collection
  end
  root "top#index"
  get "up" => "rails/health#show", as: :rails_health_check
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_to root_path, success: t(".success")
    else
      render :new, status: :unprocessable_entity

    end
  end

  def destroy
    logout
    redirect_to root_path, status: :see_other, danger: t(".success")
  end
end

app/views/user_sessions/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
    <div class="row">
      <div class=" col-md-10 col-lg-8 mx-auto">
        <h1>ログイン</h1>
        <%= form_with url: login_path do |f| %>
          <div class="mb-3">
            <%= f.label :email %>
            <%= f.email_field :email, class: "form-control", maxlength: "300" %>
          </div>
          <div class="mb-3">
            <%= f.label :password %>
            <%= f.password_field :password, class: "form-control", maxlength: "20" %>
          </div>
          <%= f.submit t('.login'), class: "btn btn-primary" %>
        <% end %>
        <div class='text-center'>
          <%= link_to t('.to_register_page'), new_user_path %>
          <%= link_to t('.password_forget'), new_password_reset_path %>
        </div>
      </div>
    </div>
  </div>